/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process liveness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Process is alive. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dependency readiness check */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service is ready. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadyResponse"];
                    };
                };
                /** @description One or more dependencies are unavailable. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReadyResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login succeeded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIResponse"] & {
                            data?: components["schemas"]["LoginData"];
                        };
                    };
                };
                400: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIResponse"] & {
                            data?: {
                                user: components["schemas"]["UserBrief"];
                            };
                        };
                    };
                };
                401: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List auctions */
        get: {
            parameters: {
                query?: {
                    status?: components["parameters"]["AuctionStatusQuery"];
                    seller_id?: number;
                    page?: components["parameters"]["PageQuery"];
                    size?: components["parameters"]["SizeQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Auction list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIResponse"] & {
                            data?: components["schemas"]["AuctionListData"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create auction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAuctionRequest"];
                };
            };
            responses: {
                /** @description Auction created. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuctionResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                401: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get auction detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    auction_id: components["parameters"]["AuctionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Auction detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuctionResponse"];
                    };
                };
                404: components["responses"]["ErrorResponse"];
            };
        };
        /** Update pending auction */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    auction_id: components["parameters"]["AuctionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateAuctionRequest"];
                };
            };
            responses: {
                /** @description Auction updated. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuctionResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                401: components["responses"]["ErrorResponse"];
                403: components["responses"]["ErrorResponse"];
                404: components["responses"]["ErrorResponse"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel auction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    auction_id: components["parameters"]["AuctionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Auction cancelled. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuctionResponse"];
                    };
                };
                401: components["responses"]["ErrorResponse"];
                403: components["responses"]["ErrorResponse"];
                404: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_id}/bid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place bid */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                };
                path: {
                    auction_id: components["parameters"]["AuctionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BidRequest"];
                };
            };
            responses: {
                /** @description Bid accepted or business rejected. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BidAcceptedResponse"] | components["schemas"]["BidBusinessRejectedResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                401: components["responses"]["ErrorResponse"];
                409: components["responses"]["ErrorResponse"];
                429: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_id}/bids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List accepted bids */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    before_bid_id?: number;
                };
                header?: never;
                path: {
                    auction_id: components["parameters"]["AuctionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Accepted bid list. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIResponse"] & {
                            data?: {
                                list: components["schemas"]["Bid"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get auction snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    auction_id: components["parameters"]["AuctionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Auction snapshot. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIResponse"] & {
                            data?: components["schemas"]["AuctionSnapshot"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auctions/{auction_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get events after sequence */
        get: {
            parameters: {
                query: {
                    after_seq: number;
                    limit?: number;
                };
                header?: never;
                path: {
                    auction_id: components["parameters"]["AuctionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event compensation result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["APIResponse"] & {
                            data?: components["schemas"]["EventListData"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders as buyer */
        get: {
            parameters: {
                query?: {
                    status?: components["parameters"]["OrderStatusQuery"];
                    page?: components["parameters"]["PageQuery"];
                    size?: components["parameters"]["SizeQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Buyer orders. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/seller": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List orders as seller */
        get: {
            parameters: {
                query?: {
                    status?: components["parameters"]["OrderStatusQuery"];
                    page?: components["parameters"]["PageQuery"];
                    size?: components["parameters"]["SizeQuery"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Seller orders. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get order detail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    order_id: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Order detail. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                403: components["responses"]["ErrorResponse"];
                404: components["responses"]["ErrorResponse"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/pay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock pay order */
        post: {
            parameters: {
                query?: never;
                header: {
                    "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                    "X-Request-Id"?: components["parameters"]["RequestId"];
                };
                path: {
                    order_id: components["parameters"]["OrderId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Payment result. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OrderResponse"];
                    };
                };
                401: components["responses"]["ErrorResponse"];
                403: components["responses"]["ErrorResponse"];
                404: components["responses"]["ErrorResponse"];
                409: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload product image */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Upload succeeded. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UploadResponse"];
                    };
                };
                400: components["responses"]["ErrorResponse"];
                401: components["responses"]["ErrorResponse"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIResponse: {
            /** @example 0 */
            code: number;
            /** @example ok */
            msg: string;
            data: unknown;
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ok" | "error";
            /** @enum {string} */
            mysql: "ok" | "error";
            /** @enum {string} */
            redis: "ok" | "error";
        };
        LoginRequest: {
            nickname: string;
            avatar?: string | null;
        };
        LoginData: {
            token: string;
            user: components["schemas"]["UserBrief"];
        };
        UserBrief: {
            /** Format: int64 */
            id: number;
            nickname: string;
            avatar: string | null;
        };
        CreateAuctionRequest: {
            title: string;
            description?: string | null;
            cover_url?: string | null;
            images?: string[] | null;
            stream_url?: string | null;
            /** Format: int64 */
            start_price: number;
            /** Format: int64 */
            price_step: number;
            /** Format: int64 */
            ceiling_price?: number | null;
            /** Format: date-time */
            start_time: string;
            duration_seconds: number;
            /** @default 30 */
            extend_seconds: number;
            /** @default 30 */
            extend_threshold: number;
        };
        UpdateAuctionRequest: {
            title?: string;
            description?: string | null;
            cover_url?: string | null;
            images?: string[] | null;
            stream_url?: string | null;
            /** Format: int64 */
            start_price?: number;
            /** Format: int64 */
            price_step?: number;
            /** Format: int64 */
            ceiling_price?: number | null;
            /** Format: date-time */
            start_time?: string;
            duration_seconds?: number;
            extend_seconds?: number;
            extend_threshold?: number;
        };
        /** @enum {string} */
        AuctionStatus: "pending" | "active" | "ended" | "cancelled";
        /** @enum {string} */
        OrderStatus: "pending_pay" | "paid" | "closed";
        Auction: {
            /** Format: int64 */
            id: number;
            title: string;
            description?: string | null;
            cover_url?: string | null;
            images?: string[] | null;
            stream_url?: string | null;
            /** Format: int64 */
            start_price: number;
            /** Format: int64 */
            price_step: number;
            /** Format: int64 */
            ceiling_price?: number | null;
            /** Format: int64 */
            current_price: number;
            current_leader?: components["schemas"]["UserBriefNullable"];
            /** Format: date-time */
            start_time: string;
            /** Format: date-time */
            end_time: string;
            /** Format: date-time */
            original_end_time: string;
            extend_seconds: number;
            extend_threshold: number;
            status: components["schemas"]["AuctionStatus"];
            /** Format: int64 */
            version: number;
            viewer_count?: number;
            /** Format: int64 */
            bid_count?: number;
            seller: components["schemas"]["UserBrief"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        UserBriefNullable: components["schemas"]["UserBrief"] | null;
        AuctionResponse: components["schemas"]["APIResponse"] & {
            data?: {
                auction: components["schemas"]["Auction"];
            };
        };
        AuctionListData: {
            list: components["schemas"]["Auction"][];
            total: number;
            page: number;
            size: number;
            /** Format: date-time */
            server_time: string;
        };
        BidRequest: {
            /** Format: int64 */
            amount: number;
        };
        Bid: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            auction_id: number;
            user: components["schemas"]["UserBrief"];
            /** Format: int64 */
            amount: number;
            /** @enum {string} */
            status: "accepted" | "rejected";
            reject_reason?: string | null;
            idempotency_key?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        BidAcceptedResponse: components["schemas"]["APIResponse"] & {
            data?: {
                bid: components["schemas"]["Bid"];
                /** Format: int64 */
                auction_version: number;
                /** Format: int64 */
                current_price: number;
                current_leader: components["schemas"]["UserBrief"];
                extended: boolean;
                /** Format: date-time */
                new_end_time: string;
                /** Format: date-time */
                server_time: string;
            };
        };
        BidBusinessRejectedResponse: components["schemas"]["APIResponse"] & {
            data?: unknown;
        };
        AuctionSnapshot: {
            auction: components["schemas"]["Auction"];
            top_bids: components["schemas"]["Bid"][];
            /** Format: int64 */
            last_event_seq: number;
            /** Format: date-time */
            server_time: string;
        };
        EventEnvelope: {
            /** @enum {string} */
            type: "snapshot" | "bid_update" | "auction_extended" | "auction_started" | "auction_ended" | "auction_cancelled" | "viewer_count";
            event_id: string;
            /** Format: int64 */
            auction_id: number;
            /** Format: int64 */
            seq: number;
            /** Format: date-time */
            server_time: string;
            data: Record<string, never>;
        };
        EventListData: {
            events: components["schemas"]["EventEnvelope"][];
            has_more: boolean;
            snapshot_required: boolean;
            /** Format: date-time */
            server_time: string;
        };
        Order: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            auction_id: number;
            winner: components["schemas"]["UserBrief"];
            seller: components["schemas"]["UserBrief"];
            /** Format: int64 */
            final_price: number;
            status: components["schemas"]["OrderStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            paid_at: string | null;
        };
        OrderResponse: components["schemas"]["APIResponse"] & {
            data?: {
                order: components["schemas"]["Order"];
            };
        };
        OrderListResponse: components["schemas"]["APIResponse"] & {
            data?: {
                list: components["schemas"]["Order"][];
                total: number;
                page: number;
                size: number;
            };
        };
        UploadData: {
            url: string;
            width: number;
            height: number;
            size: number;
        };
        UploadResponse: components["schemas"]["APIResponse"] & {
            data?: components["schemas"]["UploadData"];
        };
    };
    responses: {
        /** @description Error response. */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIResponse"];
            };
        };
    };
    parameters: {
        AuctionId: number;
        OrderId: number;
        IdempotencyKey: string;
        RequestId: string;
        PageQuery: number;
        SizeQuery: number;
        AuctionStatusQuery: components["schemas"]["AuctionStatus"];
        OrderStatusQuery: components["schemas"]["OrderStatus"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
