package realtime

import (
	"encoding/json"
	"fmt"
	"time"
)

const (
	EventSnapshot     = "snapshot"
	EventViewerCount  = "viewer_count"
	MessageTypePing   = "ping"
	MessageTypePong   = "pong"
	defaultTimeZone   = "Asia/Shanghai"
	viewerCountReason = "viewer_count_changed"
)

// EventEnvelope is the server-to-client envelope from contract-v2.md §3.
// Business events are generated by domain transactions and stored in event_outbox.
type EventEnvelope struct {
	Type       string          `json:"type"`
	EventID    string          `json:"event_id"`
	AuctionID  int64           `json:"auction_id"`
	Seq        int64           `json:"seq"`
	ServerTime string          `json:"server_time"`
	Data       json.RawMessage `json:"data"`
}

type appMessage struct {
	Type       string `json:"type"`
	ClientTime string `json:"client_time,omitempty"`
	AuctionID  int64  `json:"auction_id,omitempty"`
	Seq        int64  `json:"seq,omitempty"`
}

func nowServerTime() string {
	loc, err := time.LoadLocation(defaultTimeZone)
	if err != nil {
		loc = time.Local
	}
	return time.Now().In(loc).Format(time.RFC3339Nano)
}

func mustRawJSON(v any) json.RawMessage {
	data, err := json.Marshal(v)
	if err != nil {
		return json.RawMessage(`{}`)
	}
	return data
}

func newSnapshotEvent(auctionID int64, seq int64) EventEnvelope {
	return EventEnvelope{
		Type:       EventSnapshot,
		EventID:    fmt.Sprintf("evt_snapshot_%d_%d", auctionID, seq),
		AuctionID:  auctionID,
		Seq:        seq,
		ServerTime: nowServerTime(),
		Data: mustRawJSON(map[string]any{
			"auction":  map[string]any{"id": auctionID},
			"top_bids": []any{},
		}),
	}
}

func newViewerCountEvent(auctionID int64, businessSeq int64, current int, delta int) EventEnvelope {
	return EventEnvelope{
		Type:       EventViewerCount,
		EventID:    fmt.Sprintf("evt_viewer_%d_%d", auctionID, time.Now().UnixNano()),
		AuctionID:  auctionID,
		Seq:        businessSeq,
		ServerTime: nowServerTime(),
		Data: mustRawJSON(map[string]any{
			"viewer_count": current,
			"delta":        delta,
			"reason":       viewerCountReason,
		}),
	}
}
